# Generated by Django 5.2.1 on 2025-05-09 20:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Imagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100, verbose_name="Título")),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "imagem",
                    models.ImageField(
                        upload_to="imagens_galeria/", verbose_name="Arquivo da Imagem"
                    ),
                ),
                (
                    "data_upload",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Data de Upload"
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagem",
                "verbose_name_plural": "Imagens",
                "ordering": ["-data_upload"],
            },
        ),
    ]
